Implementacion/truco/critical_trick/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.views import login
from critical_trick.views import *

urlpatterns = patterns(
    '',
    url(r'^$',
        login, name='login'),
    url(r'^logout/$',
        logout, name='logout'),
    url(r'^register/$',
        register, name='register'),
    url(r'^menu/$',
        menu, name='menu'),
    url(r'^menu/crear_partida/$',
        crearPartida, name='crear_partida'),
    url(r'^menu/sumarse_a_partida/(?P<match_id>\d+)/$',
        sumarseAPartida, name='sumarse_a_partida'),
    url(r'^juego/(?P<match_id>\d+)/$',
        juego, name='juego'),
    url(r'^juego/(?P<match_id>\d+)/nombre_de_jugadores/$',
        nombresJugadores, name='nombres_jugadores'),
    url(r'^juego/(?P<match_id>\d+)/repartir_cartas/$',
        repartirCartas, name='repartir_cartas'),
    url(r'^juego/(?P<match_id>\d+)/cartas_del_jugador/$',
        cartasDelJugador, name='cartas_del_jugador'),
    url(r'^juego/(?P<match_id>\d+)/cartas_del_oponente/$',
        cartasDelOponente, name='cartas_del_oponente'),
    url(r'^juego/(?P<match_id>\d+)/obtener_turno/$',
        obtenerTurno, name='obtener_turno'),
    url(r'^juego/(?P<match_id>\d+)/obtener_turno_canto/$',
        obtenerTurnoCanto, name='obtener_turno_canto'),
    url(r'^juego/(?P<match_id>\d+)/jugadas/$',
        conocerJugadas, name='conocer_jugadas'),
    url(r'^juego/(?P<match_id>\d+)/seleccionar_carta/$',
        seleccionarCarta, name='seleccionar_carta'),
    url(r'^juego/(?P<match_id>\d+)/ganador_de_mano/$',
        ganadorDeMano, name='ganador_de_mano'),
    url(r'^juego/(?P<match_id>\d+)/ganador_de_ronda/$',
        ganadorDeRonda, name='ganador_de_ronda'),
    url(r'^juego/(?P<match_id>\d+)/siguiente_ronda/$',
        siguienteRonda, name='siguiente_ronda'),
    url(r'^juego/(?P<match_id>\d+)/cantar_envido/$',
        cantarEnvido, name='cantar_envido'),
    url(r'^juego/(?P<match_id>\d+)/cantar_real_envido/$',
        cantarRealEnvido, name='cantar_real_envido'),
    url(r'^juego/(?P<match_id>\d+)/cantar_falta_envido/$',
        cantarFaltaEnvido, name='cantar_falta_envido'),
    url(r'^juego/(?P<match_id>\d+)/puntos_de_envido/$',
        puntosDeEnvido, name='puntos_envido'),
    url(r'^juego/(?P<match_id>\d+)/cantar_puntos_envido/$',
        cantarPuntosEnvido, name='cantar_puntos_envido'),
    url(r'^juego/(?P<match_id>\d+)/cantar_son_buenas/$',
        cantarSonBuenas, name='cantar_son_buenas'),
    url(r'^juego/(?P<match_id>\d+)/ganador_envido/$',
        ganadorDeEnvido, name='ganador_envido'),
    url(r'^juego/(?P<match_id>\d+)/cantar_truco/$',
        cantarTruco, name='cantar_truco'),
    url(r'^juego/(?P<match_id>\d+)/cantar_quiero/$',
        cantarQuiero, name='cantar_quiero'),
    url(r'^juego/(?P<match_id>\d+)/cantar_no_quiero/$',
        cantarNoQuiero, name='cantar_no_quiero'),
    url(r'^juego/(?P<match_id>\d+)/ir_al_mazo/$',
        irAlMazo, name='ir_al_mazo'),
    url(r'^juego/(?P<match_id>\d+)/cantar_re_truco/$',
        cantarReTruco, name='cantar_re_truco'),
    url(r'^juego/(?P<match_id>\d+)/cantar_quiero_vale_cuatro/$',
        cantarQuieroValeCuatro, name='cantar_quiero_vale_cuatro'),
    url(r'^juego/(?P<match_id>\d+)/lugar_de_repartidor/$',
        lugarRepartidorDeCartas, name='lugar_de_repartidor'),
)

Implementacion/truco/truco/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^critical_trick/', include('critical_trick.urls', namespace='critical_trick')),
    url(r'^admin/', include(admin.site.urls)),
)

Implementacion/truco/critical_trick/forms.py
 # -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User
from critical_trick.models import Partida


class RegisterForm(forms.ModelForm):
    """
    Una forma que crea un usuario, sin privilegios,
    desde el nombre de usuario dado, email y contraseña.
    """
    error_messages = {
        'duplicate_username': "Un usuario con ese nombre ya existe.",
        'password_mismatch': "Los dos campos de contraseña no coinciden.",
    }

    username = forms.RegexField(
        label=("Usuario:"), max_length=30, regex=r"^[\w.@+-]+$",
        help_text=("Necesario. 30 caracteres o menos. Letras, digitos y "
                   "@/./+/-/_ solamente."),
        error_messages={
            'invalid': ("Este valor sólo puede contener letras, números y "
                        "@/./+/-/_ caracteres.")},
        widget=forms.TextInput(
            attrs={
            }
        )
    )

    password1 = forms.CharField(
        label=("Contraseña:"),
        widget=forms.PasswordInput(
            attrs={
            }
        )
    )

    password2 = forms.CharField(
        label=("Confirmar Contraseña"),
        widget=forms.PasswordInput(
            attrs={
                'type': 'password',
            }
        ),
        help_text=("Introduzca la misma contraseña que el anterior,"
                   "para verificación.")
    )

    email = forms.CharField(
        label=("Email"),
        widget=forms.TextInput(
            attrs={
                'type': 'email',
            }
        )
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    # Esto es sólo para que w3c valide como html5 el formulario
    # en la parte de required
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for _, field in self.fields.items():
            if field.widget.is_required:
                field.widget.attrs['required'] = 'required'

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(
            self.error_messages[self.error_messages['duplicate_username']],
            code='duplicate_username',
        )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages[self.error_messages['password_mismatch']],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class LoginForm(forms.ModelForm):
    """
    Forma para el ingreso del usuario al sistema
    """

    username = forms.RegexField(
        max_length=30, regex=r"^[\w.@+-]+$",
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Usuario',
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña',
            }
        )
    )

    class Meta:
        model = User
        fields = ('username', 'password')

    # Esto es sólo para que w3c valide como html5 el formulario
    # en la parte de required
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for _, field in self.fields.items():
            if field.widget.is_required:
                field.widget.attrs['required'] = 'required'


class PartidaForm(forms.ModelForm):

    class Meta:
        model = Partida
        fields = ('nombre_de_partida', 'maximo_de_jugadores', 'puntos_a_jugar')

Implementacion/truco/critical_trick/views.py
 # -*- coding: utf-8 -*-

from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
from django.contrib import messages
from django.template.response import TemplateResponse
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from critical_trick.forms import *
from critical_trick.models import *
import json
from django.views.decorators.csrf import csrf_exempt


def login(request):
    if request.method == "GET":
        form = LoginForm()
        context = {'form': form}
        return TemplateResponse(request, 'critical_trick/login.html', context)
    elif request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return redirect('critical_trick:menu')
        else:
            msg_error = "Usuario inválido o contraseña incorrecta." \
                        " Intente de nuevo"
            form = LoginForm()
            context = {'form': form, 'message': msg_error, 'error': True}
            return TemplateResponse(request, 'critical_trick/login.html',
                                    context)


def logout(request):
    auth_logout(request)
    message = "El usuario se a deslogueado exitosamente."
    messages.success(request, message)
    response = redirect('critical_trick:login')
    response.delete_cookie('user_location')
    return response


def register(request):
    if request.method == "GET":
        form = RegisterForm()
        context = {'form': form}
        return TemplateResponse(request, 'critical_trick/register.html',
                                context)
    elif request.method == "POST":
        try:
            form = RegisterForm(request.POST)
            if form.is_valid():
                form.save()
                message = ("El usuario ah sido exitosamente registrado!")
                messages.success(request, message)
                return redirect('critical_trick:login')
        except Exception as e:
            form = RegisterForm()
            context = {'form': form, 'message': e.message, 'error': True}
            return TemplateResponse(request, 'critical_trick/register.html',
                                    context)
    msg_error = form.errors.as_text
    form = RegisterForm()
    context = {'form': form, 'message': msg_error, 'error': True}
    return TemplateResponse(request, 'critical_trick/register.html', context)


@login_required
def menu(request):
    if request.method == "GET":
        request_dict = request.GET.dict()
        if not request_dict:
            if request.user.is_authenticated():
                partidas = Partida.objects.all()
                context = {'partidas': partidas}
                return TemplateResponse(request, 'critical_trick/menu.html',
                                        context)
            else:
                response = '<h1>Solo usuarios logeados pueden ingresar</h1>'
                return HttpResponse(response)
        else:
            if request_dict['estado'] == "buscando jugadores":
                partida = Partida.objects.get(id=request_dict['partida_id'])
                jugadores = Jugador.objects.filter(partida=partida)
                return HttpResponse(str(len(jugadores)))
            elif request_dict['estado'] == "actualizar mesas disponibles":
                num_partidas = len(Partida.objects.all())
                return HttpResponse(str(num_partidas))


def crearPartida(request):
    if request.method == "GET":
        form = PartidaForm()
        context = {'partidaForm': form}
        return TemplateResponse(request, 'critical_trick/crear_partida.html',
                                context)
    elif request.method == "POST":
        form = PartidaForm(request.POST)
        if form.is_valid():
            partida = form.save()
            j1 = Jugador()
            j1.crearPartida(request.user.username, partida.id)
            context = {'partida': partida}
            return TemplateResponse(request, 'critical_trick/espera.html',
                                    context)


def sumarseAPartida(request, match_id):
    try:
        partida = Partida.objects.get(id=match_id)
        jugadores = Jugador.objects.filter(partida=partida)
        if len(jugadores) < partida.maximo_de_jugadores - 1:
            j2 = Jugador()
            j2.sumarseAPartida(request.user.username, match_id)
            context = {'partida': partida}
            return TemplateResponse(request, 'critical_trick/espera.html',
                                    context)
        elif len(jugadores) == partida.maximo_de_jugadores - 1:
            j2 = Jugador()
            j2.sumarseAPartida(request.user.username, match_id)
            return redirect('critical_trick:juego', match_id=match_id)
        else:
            raise Exception("No hay lugar.\n La mesa está llena.")
    except Exception as msg_error:
        messages.success(request, msg_error)
        return redirect('critical_trick:menu')


def juego(request, match_id):
    partida = Partida.objects.get(id=match_id)
    user = User.objects.get(username=request.user.username)
    jugador = Jugador.objects.get(user=user, partida=partida)
    jugadores = Jugador.objects.filter(partida=partida)
    ronda_actual = Ronda.objects.get(partida=partida,
                                     id_ronda=partida.numero_de_rondas)
    context = {'partida': partida, 'jugadores': jugadores,
               'player': jugador, 'ronda': ronda_actual}
    if partida.maximo_de_jugadores == 2:
        response = TemplateResponse(request, 'critical_trick/2Jugadores.html', context)
    elif partida.maximo_de_jugadores == 4:
        response = TemplateResponse(request, 'critical_trick/4Jugadores.html', context)
    elif partida.maximo_de_jugadores == 6:
        response = TemplateResponse(request, 'critical_trick/6Jugadores.html', context)
    return response

def nombresJugadores(request, match_id):
    partida = Partida.objects.get(id=match_id)
    user = User.objects.get(username=request.user.username)
    jugador = Jugador.objects.get(user=user, partida=partida)
    response = jugador.nombresJugadores()
    return HttpResponse(json.dumps(response), content_type="application/json")

def repartirCartas(request, match_id):
    partida = Partida.objects.get(id=match_id)
    user = User.objects.get(username=request.user.username)
    jugador = Jugador.objects.get(user=user, partida=partida)
    response = jugador.repartirCartas()
    return HttpResponse(response)

def cartasDelJugador(request, match_id):
    partida = Partida.objects.get(id=match_id)
    user = User.objects.get(username=request.user.username)
    jugador = Jugador.objects.get(user=user, partida=partida)
    response = jugador.obtenerMisCartas()
    return HttpResponse(json.dumps(response), content_type="application/json")


def cartasDelOponente(request, match_id):
    partida = Partida.objects.get(id=match_id)
    user = User.objects.get(username=request.user.username)
    jugador = Jugador.objects.get(user=user, partida=partida)
    request_dict = request.GET.dict()
    silla = request_dict['silla']
    response = jugador.obtenerCartasDelOponente(silla)
    return HttpResponse(json.dumps(response), content_type="application/json")


def obtenerTurno(request, match_id):
    partida = Partida.objects.get(id=match_id)
    ronda_actual = Ronda.objects.get(partida=partida,
                                     id_ronda=partida.numero_de_rondas)
    return HttpResponse(ronda_actual.turno)


def obtenerTurnoCanto(request, match_id):
    partida = Partida.objects.get(id=match_id)
    ronda_actual = Ronda.objects.get(partida=partida,
                                     id_ronda=partida.numero_de_rondas)
    return HttpResponse(ronda_actual.turno_canto)


def conocerJugadas(request, match_id):
    partida = Partida.objects.get(id=match_id)
    user = User.objects.get(username=request.user.username)
    jugador = Jugador.objects.get(user=user, partida=partida)
    response = jugador.conocerJugadas()
    return HttpResponse(json.dumps(response), content_type="application/json")


def seleccionarCarta(request, match_id):
    partida = Partida.objects.get(id=match_id)
    user = User.objects.get(username=request.user.username)
    jugador = Jugador.objects.get(user=user, partida=partida)
    request_dict = request.GET.dict()
    carta = request_dict['carta']
    response = jugador.elegirCarta(carta)
    ganadorDeMano(request, match_id) # corregir
    return HttpResponse(response)


def ganadorDeMano(request, match_id):
    partida = Partida.objects.get(id=match_id)
    ronda_actual = Ronda.objects.get(partida=partida,
                                     id_ronda=partida.numero_de_rondas)
    num_mano_actual = ronda_actual.numero_de_manos_jugadas + 1
    mano = Mano.objects.get(ronda=ronda_actual, id_mano=num_mano_actual)
    response = mano.ganadorDeMano()

def ganadorDeRonda(request, match_id):
    partida = Partida.objects.get(id=match_id)
    ronda_actual = Ronda.objects.get(partida=partida,
                                     id_ronda=partida.numero_de_rondas)
    response = ronda_actual.ganadorRonda()
    return HttpResponse(response)


def siguienteRonda(request, match_id):
    # request_dict = request.GET.dict()
    # ganador = request_dict['ganador']
    partida = Partida.objects.get(id=match_id)
    partida.siguienteRonda()
    return HttpResponse()


def cantarEnvido(request, match_id):
    partida = Partida.objects.get(id=match_id)
    user = User.objects.get(username=request.user.username)
    jugador = Jugador.objects.get(user=user, partida=partida)

Implementacion/truco/critical_trick/templates/critical_trick/4Jugadores.html
{% extends "critical_trick/base.html" %}

{% block title %}En Partida! Critical Trick!{% endblock %}

{% block styles %} 
    {% load staticfiles %}
    <link href="{% static 'critical_trick/css/4Jugadores.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    <div class="contenedor">
        <div class="jugador">
            {% if player.equipo == 1 %}
                <div id="equipo_2">
                    <li> Jugadores:</li>
                    <li>(2) {{ jugadores.1 }}<br>(4) {{ jugadores.3 }}</li>
                    <li> Puntos: {{ partida.puntos_equipo2 }}</li>
                </div>
                <div id="puntos">
                    <li> Jugando por: {{ partida.puntos_a_jugar }}</li>
                </div>
                <div id="equipo_1">
                    <li>Jugadores:</li>
                    <li>(1) {{ jugadores.0 }}<br>(3) {{ jugadores.2 }}</li>
                    <li> Puntos: {{ partida.puntos_equipo1 }} </li>
                </div>
            {% else %}  
                <div id="equipo_2">
                    <li>Jugadores:</li>
                    <li>(1) {{ jugadores.0 }}<br>(3) {{ jugadores.2 }}</li>
                    <li> Puntos: {{ partida.puntos_equipo1 }} </li>
                </div>
                <div id="puntos">
                    <li> Jugando por: {{ partida.puntos_a_jugar }}</li>
                </div>
                <div id="equipo_1">
                    <li> Jugadores:</li>
                    <li>(2) {{ jugadores.1 }}<br>(4) {{ jugadores.3 }}</li>
                    <li> Puntos: {{ partida.puntos_equipo2 }}</li>
                </div>
            {% endif %}
        </div>
        <div class="mesa">
            <div id="cartas_jugador_3">
                <p class="carta" id="carta7"></p>
                <p class="carta" id="carta8"></p>
                <p class="carta" id="carta9"></p>
            </div>
            <div id="cartas_jugador_4">
                <p class="carta" id="carta10"></p>
                <p class="carta" id="carta11"></p>
                <p class="carta" id="carta12"></p>
            </div>
            <div id="cartas_jugador_1">
                <p class="carta" id="carta1"></p>
                <p class="carta" id="carta2"></p>
                <p class="carta" id="carta3"></p>
            </div>
            <div id="cartas_jugador_2">
                <p class="carta" id="carta4"></p>
                <p class="carta" id="carta5"></p>
                <p class="carta" id="carta6"></p>
            </div>
            <p class="nombre_box" id="nombre_jug1">Jugador 1</p>
            <p class="nombre_box" id="nombre_jug2">Jugador 2</p>
            <p class="nombre_box" id="nombre_jug3">Jugador 3</p>
            <p class="nombre_box" id="nombre_jug4">Jugador 4</p>
        </div>
        <div class="opciones">
            <button type="button" class="botones" id="truco">Truco</button>
            <button type="button" class="botones" id="re_truco">Re Truco</button>
            <button type="button" class="botones" id="quiero_valecuatro">Vale cuatro</button>
            <button type="button" class="botones" id="envido">Envido</button>
            <button type="button" class="botones" id="real_envido">Real Envido</button>
            <button type="button" class="botones" id="falta_envido">Falta Envido</button>
            <button type="button" class="botones" id="puntos_envido"></button>
            <button type="button" class="botones" id="son_buenas">Son Buenas</button>
            <button type="button" class="botones" id="quiero">Quiero</button>
            <button type="button" class="botones" id="no_quiero">No Quiero</button>
            <button type="button" class="botones" id="ir_al_mazo">Ir al Mazo</button>
            {% if ronda.jugador_mano != user.get_username and not ronda.cartas_repartidas %}
            <button class="botones" id="repartir" type="button" onclick="repartirCartas()">Repartir Cartas</button>
            {% endif %}
        </div>
        <div id="table_info">
            <p id="msg"></p>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'critical_trick/js/juego.js' %}"></script>
    <script type="text/javascript">

        function convertToBoolean(data) {
            var bool;
            if (data === "True") {
                bool = true
            } else if (data ==="False") {
                bool = false
            } else {
                console.log("bool convert error")
            }
            return bool
        }

        JUGADOR_MANO = "{{ ronda.jugador_mano }}"
        USERNAME = "{{ user.get_username }}"
        CARTAS_REPARTIDAS = convertToBoolean("{{ ronda.cartas_repartidas }}")
        TRUCO = convertToBoolean("{{ ronda.truco }}")
        TURNO = "{{ ronda.turno }}"
        NUMERO_JUGADORES = "{{ partida.numero_jugadores }}"
        MI_SILLA = "{{ player.silla }}"
        MI_EQUIPO = "{{ player.equipo }}"
        PUNTOS_EQUIPO1 = "{{ partida.puntos_equipo1 }}"
        PUNTOS_EQUIPO2 = "{{ partida.puntos_equipo2 }}"
        URL_NOMBRES_JUGADORES = "{% url 'critical_trick:nombres_jugadores' partida.id %}"
        URL_LUGAR_REPARTIDOR = "{% url 'critical_trick:lugar_de_repartidor' partida.id %}"
        URL_REPARTIR_CARTAS = "{% url 'critical_trick:repartir_cartas' partida.id %}"
        URL_CARTAS_DEL_JUGADOR = "{% url 'critical_trick:cartas_del_jugador' partida.id %}"
        {% load staticfiles %}
        URL_CARTA_BACK = "{% static 'critical_trick/cartas/back_blue.png' %}"
        URL_JUGADA_DEL_OPONENTE = "{% url 'critical_trick:conocer_jugadas' partida.id %}"
        URL_JUEGO = "{% url 'critical_trick:juego' partida.id %}"
        URL_MENU = "{% url 'critical_trick:menu' %}"
        URL_OBTENER_TURNO = "{% url 'critical_trick:obtener_turno' partida.id %}"
        URL_OBTENER_TURNO_CANTO = "{% url 'critical_trick:obtener_turno_canto' partida.id %}"
        URL_SELECCIONAR_CARTA = "{% url 'critical_trick:seleccionar_carta' partida.id %}"
        URL_CARTAS_DEL_OPONENTE = "{% url 'critical_trick:cartas_del_oponente' partida.id %}"
        URL_GANADOR_DE_MANO = "{% url 'critical_trick:ganador_de_mano' partida.id %}"
        URL_GANADOR_DE_RONDA = "{% url 'critical_trick:ganador_de_ronda' partida.id %}"
        URL_SIGUIENTE_RONDA = "{% url 'critical_trick:siguiente_ronda' partida.id %}"
        URL_CANTAR_ENVIDO = "{% url 'critical_trick:cantar_envido' partida.id %}"
        URL_CANTAR_REAL_ENVIDO = "{% url 'critical_trick:cantar_real_envido' partida.id %}"
        URL_CANTAR_FALTA_ENVIDO = "{% url 'critical_trick:cantar_falta_envido' partida.id %}"
        URL_CANTAR_TRUCO = "{% url 'critical_trick:cantar_truco' partida.id %}"
        URL_CANTAR_RE_TRUCO = "{% url 'critical_trick:cantar_re_truco' partida.id %}"
        URL_CANTAR_VALE_CUATRO = "{% url 'critical_trick:cantar_quiero_vale_cuatro' partida.id %}"
        URL_CANTAR_QUIERO = "{% url 'critical_trick:cantar_quiero' partida.id %}"
        URL_CANTAR_NO_QUIERO = "{% url 'critical_trick:cantar_no_quiero' partida.id %}"
        URL_GANADOR_DE_ENVIDO = "{% url 'critical_trick:ganador_envido' partida.id %}"
        URL_OBTENER_PUNTOS_ENVIDO = "{% url 'critical_trick:puntos_envido' partida.id %}"
        URL_CANTAR_PUNTOS_DE_ENVIDO ="{% url 'critical_trick:cantar_puntos_envido' partida.id %}"
        URL_CANTAR_SON_BUENAS = "{% url 'critical_trick:cantar_son_buenas' partida.id %}"
        URL_IR_AL_MAZO = "{% url 'critical_trick:ir_al_mazo' partida.id %}"

    </script>
{% endblock %}

Implementacion/truco/critical_trick/templates/critical_trick/menu.html
{% extends "critical_trick/base.html" %}

{% block title %} Juega! - Critical trick{% endblock %}

{% block styles %} 
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'critical_trick/css/menu.css' %}">
{% endblock %}

{% block content %}
    <p class="username">{{ user.get_username }} | <a href="{% url 'critical_trick:logout' %}">Cerrar Sesión</a></p>
    <header>
        <h1>Truco Argentino</h1>
        <div id="menu">
            <ul class="bmenu">
                <li><a href="{% url 'critical_trick:menu' %}">Menú</a></li>
                <li><a href="#">Tutorial</a></li>
                <li><a href="#">Nosotros</a></li>
                <li><a href="#">Contacto</a></li>
            </ul>
        </div>
    </header>
    <div id="container">
        <div id="principal">
            <button type="button" onclick="location.href='{% url 'critical_trick:crear_partida' %}'">Crear Mesa<br>(+)</button>
        </div>
        <ul id="mesas">
            <p id="titulo_mesa">Mesas Disponibles</p>
            {% for partida in partidas %}
                {% if partida.numero_jugadores < partida.maximo_de_jugadores %}
                    <a href="{% url 'critical_trick:sumarse_a_partida' partida.id %}">
                    <li>
                        <p>Nombre de Partida: {{ partida.nombre_de_partida }}</p>
                        <p>Creada hace: {{ partida.timeThatWasCreated }}</p>
                        <p>Jugadores: {{ partida.numero_jugadores }}/{{ partida.maximo_de_jugadores }}</p>
                        <p>Puntos: {{ partida.puntos_a_jugar }}</p>
                    </li>
                    </a>
                {% endif %}
            {% endfor %}
        </ul>
        {% for message in messages %}
        <div id="table_error">
            <p id="msg_error">{{ message }}</p>
            <button id="but_error" class="buttons" type="button" onclick="hideTableError()">ok</button>
        </div>
        {% endfor %}
    </div>
    <footer>
        <small>Copyright &copy; 2014 ingsoft-famaf</small>
    </footer>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'critical_trick/js/menu.js' %}"></script>
    <script type="text/javascript">
        URL_MENU = "{% url 'critical_trick:menu' %}"
        CANTIDAD_PARTIDAS = "{{ partidas|length }}"
    </script>
{% endblock %}